### ISSUE TITLE
Please provide the training result.

### ISSUE THREAD

**Issue by gaopinghai** [JZhaoCH/fbpconvnet_pytorch#1]
I have tried the train.py. But after 97 epoch of training, the result is as the pic below:
![epoch-97-iteration-200](https://user-images.githubusercontent.com/19465753/111021356-a05c3600-8406-11eb-8146-0f36a15bc28e.jpg)
 and the training loss is as:
```
loss (epoch-93-iteration-300) : 13.986238
save image: ./samples/epoch-93-iteration-400.jpg
loss (epoch-93-iteration-400) : 1.800856
save image: ./samples/epoch-94-iteration-100.jpg
loss (epoch-94-iteration-100) : 7.462033
save image: ./samples/epoch-94-iteration-200.jpg
loss (epoch-94-iteration-200) : 1.865844
save image: ./samples/epoch-94-iteration-300.jpg
loss (epoch-94-iteration-300) : 2.170855
save image: ./samples/epoch-94-iteration-400.jpg
loss (epoch-94-iteration-400) : 3.993443
save image: ./samples/epoch-95-iteration-100.jpg
loss (epoch-95-iteration-100) : 15.650680
save image: ./samples/epoch-95-iteration-200.jpg
loss (epoch-95-iteration-200) : 1.744222
save image: ./samples/epoch-95-iteration-300.jpg
loss (epoch-95-iteration-300) : 1.496086
save image: ./samples/epoch-95-iteration-400.jpg
loss (epoch-95-iteration-400) : 1.489223
save image: ./samples/epoch-96-iteration-100.jpg
loss (epoch-96-iteration-100) : 2.223736
save image: ./samples/epoch-96-iteration-200.jpg
loss (epoch-96-iteration-200) : 1.954349
save image: ./samples/epoch-96-iteration-300.jpg
loss (epoch-96-iteration-300) : 2.035094
save image: ./samples/epoch-96-iteration-400.jpg
loss (epoch-96-iteration-400) : 26.680279
save image: ./samples/epoch-97-iteration-100.jpg
loss (epoch-97-iteration-100) : 5.275980
save image: ./samples/epoch-97-iteration-200.jpg
loss (epoch-97-iteration-200) : 9.626511
```
I do not know if everything is going well. So please provide the training results for reference.

**Comment by jonzhaocn** [comment]
你好：

我是两年前复现的代码，刚才去找之前复现的结果，发现已经被我删除了。
1. 你发的图片中都是噪声，请问这幅图像是网络的输入图像吗，还是网络降噪后的结果？
2. 请问你是说97 epoch之前网络有降噪的效果，97 epoch之后，降噪的效果就变差了吗？

**Comment by gaopinghai** [comment]
> 你好：
> 
> 我是两年前复现的代码，刚才去找之前复现的结果，发现已经被我删除了。
> 
> 1. 你发的图片中都是噪声，请问这幅图像是网络的输入图像吗，还是网络降噪后的结果？
> 2. 请问你是说97 epoch之前网络有降噪的效果，97 epoch之后，降噪的效果就变差了吗？

我在去认真研究一下代码再与您交流。目前已经训练了151epoch，我去看看结果，再根据您问题中提供的信息去想想，谢谢。

**Comment by gaopinghai** [comment]
> 你好：
> 
> 我是两年前复现的代码，刚才去找之前复现的结果，发现已经被我删除了。
> 
> 1. 你发的图片中都是噪声，请问这幅图像是网络的输入图像吗，还是网络降噪后的结果？
> 2. 请问你是说97 epoch之前网络有降噪的效果，97 epoch之后，降噪的效果就变差了吗？

您好，提供的图片是网络降噪后的图片。  
并不是97之前有降噪的效果，97epoch之后就没有了。而是一直都是这样的。下面的图片是训练151个epoch之后网络处理后的图片，效果也不行：
![epoch-151-iteration-400](https://user-images.githubusercontent.com/19465753/111112205-b569ce00-859a-11eb-9876-5ff99cc7860c.jpg)

目前来说，简单的运行您的代码结果不好，不知道需要怎么调整训练手段才能得到预想的效果。谢谢！

**Comment by jonzhaocn** [comment]
不好意思，最近在忙，手头上目前也没有GPU资源，无法测试代码。之后有时间的话，我再看看。🥺

**Comment by jonzhaocn** [comment]
你好，我更新了train.py（请拉取最新的更新）。

在train.py中先使用`cmap_convert`转换sample，再进行保存。sample image的显示效果应不再是黑白，而是与readme中的图像一致。
